### ISSUE TITLE
AI attempts invalid moves for white

### ISSUE THREAD

**Issue by wildarch** [nouwaarom/GameBot#2] opened 2016-03-07 22:39 UTC
The log:
`
./host --startai
Starting publisher
Starting subscriber
Starting proxy
Welcome, I am Hansel, I am the host for this game
Do you want to start?
no
Starting Board Recognizer ...
Starting Arm Controller ...
Arbitrator Initializing
Starting AI ...
Requesting AI move ...
Recieved response
AI response: 
move {
  newpiece {
    type: "w"
    location: 11
  }
  removedpieces {
    type: "w"
    location: 5
  }
}

NewPiece location (11) is not empty
Illegal move
You need to make a move
Old location: 19
New location: 24
Removed: 19
User did clever move
Recieved response
Requesting AI move ...
Recieved response
AI response: 
move {
  newpiece {
    type: "w"
    location: 22
  }
  removedpieces {
    type: "w"
    location: 16
  }
}
`

**Comment by nouwaarom** [comment] 2016-03-08 10:49
I cannot reproduce this bug. Can you check if you can reproduce this bug.

**Comment by wildarch** [comment] 2016-03-22 21:48
I believe to have finally found the cause for this strange behaviour: The ai process remains running in the background, even after killing the app and the bus. Working on a fix to auto kill the ai now

**Comment by wildarch** [comment] 2016-03-22 22:23
#9 Should fix this

**Comment by nouwaarom** [comment] 2016-03-22 23:48
Fixed by #9

**Closed as completed by nouwaarom** 2016-03-22 23:48 UTC
